name: 'CodeDeploy'
description: 'Create a CodeDeploy Deployment'
inputs:
  application-name:
    description: 'CodeDeploy Application Name'
    required: true
  deployment-group-name:
    description: 'CodeDeploy Deployment Group Name'
    required: true
  appspec-file:
    description: 'AppSpec file'
    required: true
  max-wait-time:
    description: 'Maximum time to wait for CodeDeploy to complete'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
