 name: "Test"
 on:
   pull_request:
   push:
     branches:
       - master
       - 'v*'
 env:
   node_version: "12.x"

 jobs:
   build: # make sure build/ci work properly
     name: Build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - name: Set up Node.js
         uses: actions/setup-node@v1
         with:
           node-version: ${{ env.node_version }}

       - name: npm install
         run: npm install

       - name: npm build
         run: npm build

       - name: npm run pack
         run: npm run package

   audit:
     name: Audit
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: Set up Node.js
         uses: actions/setup-node@v1
         with:
           node-version: ${{ env.node_version }}

       - name: npm audit
         run: npm audit --audit-level=critical

   lint:
     name: Lint
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - name: Set up Node.js
         uses: actions/setup-node@v1
         with:
           node-version: ${{ env.node_version }}

       - name: npm install
         run: npm install

       - name: npm lint
         run: npm run lint

# No node tests setup yet

#   test:
#     name: Test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#
#       - name: Set up Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ env.node_version }}
#
#       - name: npm install
#         run: npm install
#
#       - name: npm test
#         run: npm test

#   test:
#     name: Test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: CodeDeploy
#         uses: ./
#         with:
#           application-name: some-cd-app
#           deployment-group-name: some-cd-group
#           appspec-file: some-appspec-file

# I really don't know the best way to test this, so commenting it all out for now.
# A test would require setting up an application (probably with terraform).
# Just use https://github.com/byu-oit/hello-world-api and https://github.com/byu-oit/hw-lambda-api to test for now.
